name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v1.1.0
      env:
        JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
    - name: Ping
      run: jfrog rt ping
    - name: jfrog Configure Resolver
      run: jfrog rt dotnet-config --repo-resolve "nuget-dev" --server-id-resolve "${{ secrets.JFROG_SERVER_NAME }}"
    - name: jfrog dotnet restore
      # adding build-name and build-number adds deps info to the build-info object, which can then be published with jfrog rt build-publish
      # the build name would be static, but the build-number could be the tag or some other unique identifier
      run: jfrog rt dotnet restore --build-name=my-build-name --build-number=1
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    #- name: Upload artifact
    #  run: jfrog rt u path-to-binary/ nuget-dev/art-name/
    #- name: Publish build.info
    #  run: |
        # Collect environment variables for the build
        # jfrog rt bce
        # Collect VCS details from git and add them to the build
        # jfrog rt bag
        # Publish build info
        # jfrog rt bp
